### ISSUE TITLE
Language can't translate properly on Kolibri studio beta 

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/le-utils#56]
## Summary
I tried to create a new channel and I observed there is a language that can't translate properly.

## Category

Select one: ENHANCEMENT

## Usage Details

*Please give details about how you were using Studio.*

 - Browser: Firefox 66.0.3 (64-bit)
 - Channel: ?
 - Topic/Content Item: ?

## Traceback or relevant snippet from browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Sign in as user
2. Create a new channel
3. at the language selection you will see the  `Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔`

## Screenshots
![Language cant translate in kolibri studio](https://user-images.githubusercontent.com/38421180/56258820-7fe4ad80-6103-11e9-9fca-d96f513c71d5.png)
## Real-life consequences (anything community should be aware of, for instance how it affects end users)

*If applicable*

**Comment by aronasorman** [comment]
Yup, no one uses baybayin anymore. Maybe the real and easiest fix here is to just remove that script from the tagalog name!
