### ISSUE TITLE
LE Utils should not contain user-facing text

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/le-utils#70]
LE utils contains some text that is used for display purposes, specifically the names and descriptions in https://github.com/learningequality/le-utils/blob/master/le_utils/resources/licenselookup.json

This is problematic for a few reasons...

* The descriptions are not translated: https://github.com/learningequality/kolibri/issues/2371

* The terms used are not consistent. E.g. "works", "resources", "content", "adapt", "change", "creator", "author", etc... This is especially bad for translators.

* The way the names are written do not conform with our writing style guidelines. For example, "All Rights Reserved" should be "All rights reserved":

  https://github.com/learningequality/le-utils/blob/5c33968a049af889fddf5271b41f67e95a1c7812/le_utils/resources/licenselookup.json#L51

* The descriptions are written from the perspective of a content creator only, so they don't make sense to a learner or coach: https://github.com/learningequality/kolibri/issues/5569

  https://github.com/learningequality/le-utils/blob/5c33968a049af889fddf5271b41f67e95a1c7812/le_utils/resources/licenselookup.json#L8

* The CC descriptions are copied from the creative commons website, and are written from the perspective of the CC org:

  https://github.com/learningequality/le-utils/blob/5c33968a049af889fddf5271b41f67e95a1c7812/le_utils/resources/licenselookup.json#L48

In https://github.com/learningequality/kolibri/pull/6042 we stopped displaying the user-facing text in LE Utils.

As far as I can tell, they are not used by studio:

![image](https://user-images.githubusercontent.com/2367265/68535971-e425c380-0318-11ea-9ab4-b1c536404536.png)

**Comment by indirectlylit** [comment]
cc @jayoshih

**Comment by rtibbles** [comment]
I think there's a more general thing here - that we simply shouldn't be drawing user facing text from LE Utils at all.

**Comment by indirectlylit** [comment]
indeed

**Comment by indirectlylit** [comment]
regarding LE-specific terminology, the glossary in the design system should now be the source of truth:

https://design-system.learningequality.org/glossary/
