### ISSUE TITLE
setup.py doesn't specify encoding when reading README.md

### ISSUE THREAD

**Issue by kollivier** [learningequality/le-utils#72]
In the fallback codepath for reading `README.md` in `setup.py` open does not specify an encoding, nor convert the text. This can cause the file to be read in as ASCII, which will error out because the file is encoded in UTF-8 and contains non-ASCII text in it (Français).

There are workarounds, so this is not a huge priority, but it can be confusing because the error can happen when running pip install.

**Comment by ivanistheone** [comment]
Fixed in https://github.com/learningequality/le-utils/pull/74
